#
# SITE SETTINGS
#

# base of your site relative to the root of the Web site, eg / or ""
baseurl: ""
# URL of your site, eg https://cfrioux.github.io
url: "https://cfrioux.github.io"

# site information
title: Clémence Frioux
pronounsfirst: she
pronounssecond: her
description: > # this means to ignore newlines until the next tag
  Research scientist
  Inria
  Bordeaux, France
author: Clémence Frioux
blog_dir: /blog
permalink: /blog/posts/:year/:month/:day/:title/ # prefixed style
category_dir: /blog/categories/
category_title_prefix: "category: "

# author information
picture: https://pbs.twimg.com/profile_images/1397297499875024898/U4h44heq_400x400.jpg
email: (firstname).(lastname)@inria.fr
networks:
  twitter:
    url: https://twitter.com/
    username: c_frioux
  github:
    url: https://github.com/
    username: cfrioux
  linkedin:
    url: https://www.linkedin.com/
    username: in/clemencefrioux
  mastodon:
    url: https://mamot.fr/@
    username: clemencefrioux
  scholar:
    url: https://scholar.google.com/citations?user=
    username: ILXDngoAAAAJ
  orcid:
    url: https://orcid.org/
    username: 0000-0003-2114-0697
  researchgate:
    url: https://www.researchgate.net/profile/
    username: Clemence-Frioux

# google analytics
analytics_id: UA-115007039-1

# contacts
contacts:
  research:
    email: (firstname).(lastname)@inria.fr
    address: >
      Inria Bordeaux Sud-Ouest<br/>
      200 avenue de la Vieille Tour<br/>
      33405 Talence<br/>
      France
    direction:
      map: https://www.openstreetmap.org/way/182389279
      public_transportation:
        stop:
        link:

# research
research:
  presentation:
    overview: true
    thesis: false
    publications: true
    software: true
  restriction:
      publications: 10
      latest: 2

# apparence of posts

# apparence of buttons
link_btn_size: btn-xs
link_btn_color: btn-primary
publications_btn_size: btn-xs
publications_btn_color: btn-default
publications_btn_textcolor: text-primary

# alerts
alerts:
  no-javascript:
    danger: true
    warning: true
    information:  true

# bibliography
kind:
  label: pp_kind # label used in .bib files to denote the kind (international/national) of references
  separate:  # should international/national references be separated: (true | false)
    article: false
    inbook: false
    inproceedings: false


scholar:
  style: _bibliography/mystyle.csl
  locale: en
  sort_by: year, pp_rank
  order: descending
  group_by: none
  group_order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  use_raw_bibtex_entry: false
  bibtex_skip_fields: [pp_shortbooktitle, pp_rank, pp_kind]
  # details_dir:    bibliography
  # details_layout: bibtex.html
  # details_link:   Details
  query: "@*"

# other settings
exclude:  ['Gemfile*', '*.sh', 'update_site.sh', 'vendor']
plugins:
  - jekyll-scholar
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem]
markdown: kramdown
highlighter: rouge
kramdown:
     # input: GFM
     syntax_highlighter: rouge
