#
# SITE SETTINGS
#

# base of your site relative to the root of the Web site, eg / or ""
baseurl: ""
# URL of your site, eg https://cfrioux.github.io
url: "https://cfrioux.github.io"

# site information
title: Clémence Frioux
description: > # this means to ignore newlines until the next tag
  PhD Student at Inria
  Univ Rennes 1
  Rennes, France
author: Clémence Frioux
blog_dir: /blog
permalink: /blog/posts/:year/:month/:day/:title/ # prefixed style
category_dir: /blog/categories/
category_title_prefix: "category: "

# author information
picture: https://pbs.twimg.com/profile_images/970296961726283777/Hd0L7-N6_400x400.jpg
email: firstname.lastname@inria.fr
networks:
  twitter:
    url: https://twitter.com/
    username: c_frioux
  github:
    url: https://github.com/
    username: cfrioux
  linkedin:
    url: https://www.linkedin.com/
    username: in/clemencefrioux

# google analytics
analytics_id: UA-115007039-1

# contacts
contacts:
  research:
    email: firstname.lastname@inria.fr
    address: >
      Inria Rennes<br/>
      Campus de Beaulieu<br/>
      263 Avenue du Général Leclerc<br/>
      35042 Rennes<br/>
      France
    direction:
      map: https://goo.gl/maps/J29f2hQQ1wx
      public_transportation:
        stop:
        link:

# research
research:
  presentation:
    overview: true
    publications: true
  restriction:
      publications: 10

# apparence of posts

# apparence of buttons
link_btn_size: btn-xs
link_btn_color: btn-primary
publications_btn_size: btn-xs
publications_btn_color: btn-default
publications_btn_textcolor: text-primary

# alerts
alerts:
  no-javascript:
    danger: true
    warning: true
    information:  true

# bibliography
kind:
  label: pp_kind # label used in .bib files to denote the kind (international/national) of references
  separate:  # should international/national references be separated: (true | false)
    article: true
    inbook: false
    inproceedings: true


scholar:
  style: _bibliography/mystyle.csl
  locale: en
  sort_by: year, pp_rank
  order: descending
  group_by: none
  group_order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  use_raw_bibtex_entry: false
  bibtex_skip_fields: [pp_shortbooktitle, pp_rank, pp_kind]
  # details_dir:    bibliography
  # details_layout: bibtex.html
  # details_link:   Details
  query: "@*"

# other settings
exclude:  ['Gemfile*', '*.sh', 'update_site.sh']
plugins:
  - jekyll-scholar
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem]
markdown: kramdown
highlighter: rouge
kramdown:
     # input: GFM
     syntax_highlighter: rouge
