# Name of your GitHub Actions workflow.
name: Publish to GitHub Pages

# Specifies to run this workflow whenever a push is made (commits are
# added) to the branch named `master`.
on:
  push:
    branches:
      # Change this to the branch where you keep your Jekyll code.
      - master

# Define a job named `build-and-publish` in your workflow.
jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building a jekyll site from configured directory, maybe deploying it.
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          # GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          # GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          JEKYLL_ROOT: "src/"
          REMOTE_BRANCH: "gh-pages"
        uses: agentd00nut/jekyll-build-optional-deploy-gh-pages@master
